[project]
name = 'upgrade'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.upgradeable-contract]
path = 'contracts/upgradeable-contract.clar'
clarity_version = 3
epoch = 3.1

[contracts.implementation-v1]
path = 'contracts/implementation-v1.clar'
clarity_version = 3
epoch = 3.1

[contracts.implementation-v2]
path = 'contracts/implementation-v2.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
